fix: build failures of client apps
Before the fix I was getting the below exception during build

Failed to construct transformer:
Error: TreeFS: Could not add directory node_modules/react-native-provenance-sdk,
  adding node_modules/react-native-provenance-sdk/package.json.
  node_modules/react-native-provenance-sdk already exists in the file map as a file.
    at TreeFS.bulkAddOrModify (/Users/vasylpedak/code/demo-store/demo-store/node_mo

Because of that the app was not able to build